### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by josh146** [co9olguy/qasm-parser#9]
The beginnings of a test suite have been added in #8; the existing tests only test the `ArithmeticOp` class at the moment. However, we should extend this to include unit tests, plus integration tests that run on the example QASM scripts.

**Comment by therooler** [comment]
I can work on improving the test suite today.

**Comment by co9olguy** [comment]
@therooler Great! Let us know if you have any questions. 
Note that everything is still very much at a prototyping level, so if things don't make sense, nothing is set in stone yet

**Comment by therooler** [comment]
Cool. Btw, are you guys on Python 3.8 as well? And do you have:
```
pytest==6.1.0
lark-parser==0.10.0
sympy==1.6.2
```
?

**Comment by co9olguy** [comment]
For what it's worth, I'm using Python 3.7, `lark-parser==0.9.0` and `sympy==1.6.2` (no pytest installed in this env yet), but I don't think you'll see any difference using newer versions
